Web/Models/ErrorViewModel.cs
namespace VolkDiet.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Models/SetupModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using VolkDiet.Core.Data;

namespace VolkDiet.Models
{
    public class SetupModel
    {
        public SetupModel()
        {
            Providers = new List<SelectListItem>();
        }
        public string? newurl { get; set; }
        public string server { get; set; }
        public string database { get; set; }
        public string? user { get; set; }
        public string? password { get; set; }
        public bool trusted { get; set; }


        public ProviderType provider { get; set; }
        /// <summary>
        /// list of providers
        /// </summary>
        public List<SelectListItem> Providers { get; set; }

    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VolkDiet.Core.Caching;

using VolkDiet.Models;
using VolkDiet.WebCore.Mvc;

namespace VolkDiet.Controllers
{
    /// <summary>
    /// TODO:remove on production, only for test
    /// </summary>
    public class CacheTestModel
    {
        [ ResourceDisplayName("testmodel.current")]
        public DateTime CurrentDateTime { get; set; }

        [ResourceDisplayName("testmodel.cached")]

        public DateTime CachedDateTime { get; set; }


    }
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICacheManager _cacheManager;

        public HomeController(ILogger<HomeController> logger,
                ICacheManager cacheManager)
        {
            _logger = logger;
            _cacheManager = cacheManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            var key = _cacheManager.CreateKeyOnCache(new CachedObject("datetime.cached"));
            var value=_cacheManager.Get(key,() => DateTime.Now);
            CacheTestModel model = new CacheTestModel();
            model.CurrentDateTime=DateTime.Now;
            model.CachedDateTime = value;

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/SetupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VolkDiet.Core.Data;
using VolkDiet.Models;

namespace VolkDiet.Controllers
{
    
    public class SetupController : Controller
    {
        /// <summary>
        /// this path is called when setting database 
        /// </summary>
        /// <returns></returns>
        public  IActionResult IndexSetup()
        {
            if (/*DBSettings.IsDbInstalled()*/false)
                return RedirectToRoute(WebDefaults.HOME_PAGE);

            var model = new SetupModel
            { 
                provider= ProviderType.MsSql
            };
            FillProviders(ref model);
            return View(model);
        }

        private void FillProviders(ref SetupModel model)
        {
            var dbtypes = DBSettings.GetAllProviders();

            model.Providers.AddRange(dbtypes.Select(
                s => new SelectListItem {
                    Value=s.Key.ToString(),
                    Text=s.Value
                })
            );
            
        }
        /// <summary>
        /// this path is called when database setup  starts
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public virtual async Task<IActionResult> IndexSetup(SetupModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                IDataProvider dataProvider;
                switch (model.provider)
                {
                    case ProviderType.MsSql:
                            dataProvider = new MsSqlDataProvider();
                        break;
                    case ProviderType.PgSql:
                            dataProvider = new PgSqlDataProvider();
                        break;
                    default:
                        throw new Exception("Wrong Db Type");

                };
                string connectionstring = dataProvider.MakeConnString(model.database, model.server, model.trusted, model.user, model.password);

                dataProvider.SetConnectionString(connectionstring);
                if (! await dataProvider.DbExistsAsync())
                    dataProvider.CreateDb();

                dataProvider.InitDb();

                return View(new SetupModel {newurl=WebDefaults.HOME_PAGE });
            }
            catch (Exception ex)
            {
                //..
                ModelState.AddModelError("", $"Setup failed {ex.Message}");
            }
            return View(model);
            

        }
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web/Views/Setup/IndexSetup.cshtml
@model VolkDiet.Models.SetupModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Setup</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
  
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolkDiet.styles.css" asp-append-version="true" />

    <style>
        .row {
            padding:5px;
        }
        
        .setup-label{
            text-align:right;
        }

        .setup-head{
            padding: 1px 2px;
            margin-bottom: 0;
            background-color: rgba(0,0,0,.1);
            border-bottom: 1px solid rgba(0,0,0,.2);
        }
    </style>

</head>

<body>


 <form asp-action="IndexSetup" asp-controller="Setup" id="frmInstall" method="post">
  

     <div>
        
         
         
         <div class="row">
            
             <div class="col-12">
                     <p class="setup-head">Database setup</p>
             </div>

         </div>

         <div class="row">
             <div class="col-5">
                 <p class="setup-label">Server</p>
             </div>
             <div class="col-7">
                     <input asp-for="server" class="form-control" />
             </div>

         </div>


         <div class="row">
             <div class="col-5">
                 <p class="setup-label">Database</p>
             </div>
             <div class="col-7">
                    <input asp-for="database" class="form-control" value="_nop" />
             </div>

         </div>


         <div class="row">
             <div class="col-5">
                  <p class="setup-label">User</p>
             </div>
             <div class="col-7">
                     <input asp-for="user" class="form-control" value="alan" />
             </div>

         </div>
   
         
         <div class="row">
             <div class="col-5">
                 <p class="setup-label">Password</p>
             </div>
             <div class="col-7">
                        <input asp-for="password" class="form-control" value="x" />
             </div>

         </div>


         <div class="row">
             <div class="col-5">
                 <p class="setup-label">Database provider</p>
             </div>
             <div class="col-7">
                    <select asp-for="provider" asp-items="Model.Providers" class="form-control"></select>
             </div>

         </div>



          <div class="row">
             <div class="col-12 text-center">
                <button type="submit" class="btn btn-warning">Install</button>
             </div>
          </div>  
     </div>

 </form>
 </body>
 </html>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VolkDiet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolkDiet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VolkDiet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VolkDiet @($"{VDVersion.FULL_VERSION} ({VDWebVersion.WEB_VERSION})") - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>